from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import TEXT,Boolean,DateTime,Enum,ForeignKey,Index,Integer,String,event,func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.logger import logging
from app.exception import CustomException

if TYPE_CHECKING:
    from app.db.models.patient import Patient


SESSION_CHANNELS = ("web", "whatsapp", "kiosk", "api")
MESSAGE_ROLES = ("human", "ai", "system")
TIME_SLOT_PREFERENCES = ("morning", "afternoon", "evening", "any")


class ConversationSession(Base):
    """
    Maps to the `conversation_sessions` table.

    One row per patient chat session.  Acts as the parent record for all
    ConversationMemory rows belonging to that session.

    Session lifecycle
    -----------------
    created   → FastAPI creates row, Redis session initialised
    active    → is_active=True, last_active_at updated on each turn
    expired   → Redis TTL fires; is_active=False set by cleanup task
    archived  → ConversationMemory rows written, Redis key evicted

    patient_id is nullable because patients can chat before authenticating
    (e.g. general info queries).  Authentication flow sets patient_id
    mid-session via the auth_agent node.

    metadata JSON
    -------------
    Stores device info, detected language, A/B test flags, etc.
    Never stores PHI.  SQLite represents JSON as TEXT — the application
    layer serialises/deserialises manually for SQLite compatibility.
    """

    __tablename__ = "conversation_sessions"

    __table_args__ = (
        Index("idx_session_patient", "patient_id"),
        Index("idx_session_active", "is_active", "last_active_at"),
    )

    session_id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        comment="UUID4 generated by FastAPI session manager, e.g. 'sess_<uuid>'.",
    )

    patient_id: Mapped[Optional[str]] = mapped_column(
        String(20),
        ForeignKey("patients.patient_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    started_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        server_default=func.now(),
    )
    last_active_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        comment="Updated on every message turn. Used by TTL cleanup task.",
    )

    channel: Mapped[str] = mapped_column(
        Enum(*SESSION_CHANNELS, name="session_channel_enum"),
        nullable=False,
        default="web",
        comment="Interface the patient is using for this session.",
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        index=True,
        comment="False once Redis TTL fires or patient explicitly ends session.",
    )

    metadata_json: Mapped[Optional[str]] = mapped_column(
        "metadata",
        TEXT,
        nullable=True,
        comment=(
            "JSON: device, language_preference, ab_flags. "
            "Never contains PHI. Column name is 'metadata' in MySQL."
        ),
    )

    messages: Mapped[List["ConversationMemory"]] = relationship(
        "ConversationMemory",
        back_populates="session",
        cascade="all, delete-orphan",
        lazy="select",
        order_by="ConversationMemory.created_at",
    )

    def __repr__(self) -> str:
        return (
            f"<ConversationSession id={self.session_id!r} "
            f"channel={self.channel!r} active={self.is_active} "
            f"patient={self.patient_id!r}>"
        )


class ConversationMemory(Base):
    """
    Maps to the `conversation_memory` table.

    Archives individual message turns from Redis to MySQL.

    Write strategy
    --------------
    Turns are NOT written one-by-one during a live session — that would
    create excessive DB writes and latency.  Instead:
      - Live turns live in Redis (Tier 2)
      - The memory module writes batches to this table:
          a) On session end (all turns)
          b) Every N turns (configurable sliding archive)
          c) For emergency interactions (immediate, mandatory)

    LLM-based summarisation
    -----------------------
    For long sessions, the memory module uses a lightweight LLM
    (Phi-3 mini / Qwen2.5-3B via Groq) to compress turn batches
    into a shorter summary before archiving.  This reduces storage
    while preserving the semantic content needed for future sessions.

    The agent_name column lets the system reconstruct which sub-agent
    produced each AI response — useful for debugging and for loading
    the correct agent context on session resume.
    """

    __tablename__ = "conversation_memory"

    __table_args__ = (
        Index("idx_session_memory", "session_id", "created_at"),
        Index("idx_memory_patient", "patient_id"),
    )

    memory_id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )

    session_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("conversation_sessions.session_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    patient_id: Mapped[Optional[str]] = mapped_column(
        String(20),
        ForeignKey("patients.patient_id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    role: Mapped[str] = mapped_column(
        Enum(*MESSAGE_ROLES, name="message_role_enum"),
        nullable=False,
        comment="human = patient input, ai = agent response, system = injected context.",
    )

    content: Mapped[str] = mapped_column(
        TEXT,
        nullable=False,
        comment=(
            "Message text. May contain patient-spoken PHI — "
            "protected by AES-256 tablespace encryption in MySQL."
        ),
    )

    agent_name: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        index=True,
        comment="Sub-agent that generated this response. NULL for human/system roles.",
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        server_default=func.now(),
    )

    session: Mapped["ConversationSession"] = relationship(
        "ConversationSession",
        back_populates="messages",
        lazy="select",
    )

    def __repr__(self) -> str:
        preview = self.content[:40].replace("\n", " ") if self.content else ""
        return (
            f"<ConversationMemory id={self.memory_id} "
            f"role={self.role!r} agent={self.agent_name!r} "
            f"session={self.session_id!r} preview={preview!r}>"
        )


class PatientLongTermContext(Base):
    """
    Maps to the `patient_long_term_context` table.

    One row per patient — preference signals accumulated across sessions.
    Loaded into LangGraph state at session start for known patients so
    the Supervisor Agent can personalise routing without asking repeated
    questions.

    PHI restriction
    ---------------
    This table stores ONLY non-PHI preference metadata:
      - preferred_doctor (FK integer — no name stored here)
      - preferred_time_slot (morning/afternoon/evening/any)
      - language_preference (ISO 639-1 code, e.g. 'en', 'bn')
      - communication_opt_in (Boolean consent flag)
      - last_concern (free text — see note below)

    last_concern note
    -----------------
    This field stores a brief, non-clinical summary of the last topic
    the patient raised, e.g. "asked about appointment rescheduling" or
    "inquired about lab result availability".  It must NEVER contain
    diagnosis, medication names, or test values — those live in the
    clinical tables and audit log only.

    Upsert pattern
    --------------
    The memory module uses INSERT ... ON DUPLICATE KEY UPDATE in MySQL
    (or SQLAlchemy's merge() for portability) since there is exactly one
    row per patient_id (UNIQUE constraint).
    """

    __tablename__ = "patient_long_term_context"

    context_id: Mapped[int] = mapped_column(
        Integer, primary_key=True, autoincrement=True
    )

    patient_id: Mapped[str] = mapped_column(
        String(20),
        ForeignKey("patients.patient_id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="One-to-one with patients table.",
    )

    preferred_doctor: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("doctors.doctor_id", ondelete="SET NULL"),
        nullable=True,
        comment="FK to doctor — set when patient consistently books the same doctor.",
    )
    preferred_time_slot: Mapped[Optional[str]] = mapped_column(
        Enum(*TIME_SLOT_PREFERENCES, name="time_slot_pref_enum"),
        nullable=True,
        comment="Patient's preferred appointment time of day.",
    )
    language_preference: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        default="en",
        comment="ISO 639-1 code. Drives response language selection in the Supervisor.",
    )
    communication_opt_in: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        comment="False = patient has opted out of SMS/email notifications.",
    )

    last_concern: Mapped[Optional[str]] = mapped_column(
        TEXT,
        nullable=True,
        comment=(
            "Brief non-clinical summary of last patient topic, e.g. "
            "'asked about appointment reschedule'. "
            "MUST NOT contain diagnosis, medication, or test data."
        ),
    )

    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        onupdate=func.now(),
        comment="Auto-updated by SQLAlchemy on every change.",
    )

    patient: Mapped["Patient"] = relationship(
        "Patient",
        back_populates="long_term_context",
        lazy="select",
        uselist=False,
    )

    def __repr__(self) -> str:
        return (
            f"<PatientLongTermContext patient={self.patient_id!r} "
            f"lang={self.language_preference!r} "
            f"preferred_doctor={self.preferred_doctor} "
            f"opt_in={self.communication_opt_in}>"
        )


# Lifecycle event listeners — log memory model changes & catch errors
@event.listens_for(ConversationSession, "after_insert")
def _log_session_insert(mapper, connection, target: ConversationSession) -> None:
    try:
        logging.info(
            "ConversationSession created: id=%s, channel=%s, patient=%s",
            target.session_id, target.channel, target.patient_id,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationSession insert event.")
        raise CustomException(
            error_message="Failed to process ConversationSession insert event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(ConversationSession, "after_update")
def _log_session_update(mapper, connection, target: ConversationSession) -> None:
    try:
        logging.info(
            "ConversationSession updated: id=%s, active=%s, patient=%s",
            target.session_id, target.is_active, target.patient_id,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationSession update event.")
        raise CustomException(
            error_message="Failed to process ConversationSession update event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(ConversationSession, "after_delete")
def _log_session_delete(mapper, connection, target: ConversationSession) -> None:
    try:
        logging.info(
            "ConversationSession deleted: id=%s, channel=%s, patient=%s",
            target.session_id, target.channel, target.patient_id,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationSession delete event.")
        raise CustomException(
            error_message="Failed to process ConversationSession delete event.",
            error_detail=str(exc),
        ) from exc


@event.listens_for(ConversationMemory, "after_insert")
def _log_memory_insert(mapper, connection, target: ConversationMemory) -> None:
    try:
        logging.info(
            "ConversationMemory created: id=%d, session=%s, role=%s, agent=%s",
            target.memory_id, target.session_id, target.role, target.agent_name,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationMemory insert event.")
        raise CustomException(
            error_message="Failed to process ConversationMemory insert event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(ConversationMemory, "after_update")
def _log_memory_update(mapper, connection, target: ConversationMemory) -> None:
    try:
        logging.info(
            "ConversationMemory updated: id=%d, session=%s, role=%s",
            target.memory_id, target.session_id, target.role,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationMemory update event.")
        raise CustomException(
            error_message="Failed to process ConversationMemory update event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(ConversationMemory, "after_delete")
def _log_memory_delete(mapper, connection, target: ConversationMemory) -> None:
    try:
        logging.info(
            "ConversationMemory deleted: id=%d, session=%s, role=%s",
            target.memory_id, target.session_id, target.role,
        )
    except Exception as exc:
        logging.exception("Logging failure in ConversationMemory delete event.")
        raise CustomException(
            error_message="Failed to process ConversationMemory delete event.",
            error_detail=str(exc),
        ) from exc


@event.listens_for(PatientLongTermContext, "after_insert")
def _log_context_insert(mapper, connection, target: PatientLongTermContext) -> None:
    try:
        logging.info(
            "PatientLongTermContext created: patient=%s, lang=%s",
            target.patient_id, target.language_preference,
        )
    except Exception as exc:
        logging.exception("Logging failure in PatientLongTermContext insert event.")
        raise CustomException(
            error_message="Failed to process PatientLongTermContext insert event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(PatientLongTermContext, "after_update")
def _log_context_update(mapper, connection, target: PatientLongTermContext) -> None:
    try:
        logging.info(
            "PatientLongTermContext updated: patient=%s, lang=%s",
            target.patient_id, target.language_preference,
        )
    except Exception as exc:
        logging.exception("Logging failure in PatientLongTermContext update event.")
        raise CustomException(
            error_message="Failed to process PatientLongTermContext update event.",
            error_detail=str(exc),
        ) from exc

@event.listens_for(PatientLongTermContext, "after_delete")
def _log_context_delete(mapper, connection, target: PatientLongTermContext) -> None:
    try:
        logging.info(
            "PatientLongTermContext deleted: patient=%s, lang=%s",
            target.patient_id, target.language_preference,
        )
    except Exception as exc:
        logging.exception("Logging failure in PatientLongTermContext delete event.")
        raise CustomException(
            error_message="Failed to process PatientLongTermContext delete event.",
            error_detail=str(exc),
        ) from exc

# Wire back-reference onto Patient
def _patch_back_references() -> None:
    """Add long_term_context back-reference to Patient (one-to-one)."""
    try:
        from app.db.models.patient import Patient

        if not hasattr(Patient, "long_term_context"):
            Patient.long_term_context = relationship(
                "PatientLongTermContext",
                back_populates="patient",
                lazy="select",
                uselist=False,
                cascade="all, delete-orphan",
            )
        logging.debug("Long term context back-reference patched onto Patient successfully.")
    except Exception as exc:
        logging.exception("Failed to patch long term context back-reference onto Patient.")
        raise CustomException(
            error_message="Failed to wire long term context back-reference for Patient.",
            error_detail=str(exc),
        ) from exc


_patch_back_references()